apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-pods
  labels:
    app: s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3
  template:
    metadata:
      labels:
        app: s3
    spec:
      containers:
        - name: s3
          image: docker.io/mathieuplateforme/mys3:1.0.2
          ports:
            - containerPort: 8080